const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Turret,
		C3.Plugins.video,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Audio.Acts.SetPaused
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Ground: 0},
	{HP: 0},
	{Platform: 0},
	{TheDanny: 0},
	{Keyboard: 0},
	{Platform1: 0},
	{Bullet: 0},
	{Hammer: 0},
	{Action: 0},
	{PrevAction: 0},
	{HammerHits: 0},
	{MrWhite: 0},
	{Wall: 0},
	{Edge: 0},
	{EdgeJump: 0},
	{EdgeDoubleJump: 0},
	{Background1: 0},
	{BackgroundStart: 0},
	{StartButton: 0},
	{Mouse: 0},
	{DeathBackground: 0},
	{TryAgain: 0},
	{Quit: 0},
	{Background2: 0},
	{BackgroundTimeZone: 0},
	{TimerBox: 0},
	{Timer: 0},
	{BackgroundGinger: 0},
	{PlatformGinger: 0},
	{HammerHitsEater: 0},
	{Turret: 0},
	{TimeEater: 0},
	{TimeBullet: 0},
	{TimeEaterSprite: 0},
	{MrChidester: 0},
	{BackgroundWin: 0},
	{Video: 0},
	{TimeHole: 0},
	{TimeHoleEnd: 0},
	{Audio: 0}
];

self.InstanceType = {
	Ground: class extends self.ISpriteInstance {},
	TheDanny: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Platform1: class extends self.ISpriteInstance {},
	Hammer: class extends self.ISpriteInstance {},
	MrWhite: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Edge: class extends self.ISpriteInstance {},
	EdgeJump: class extends self.ISpriteInstance {},
	EdgeDoubleJump: class extends self.ISpriteInstance {},
	Background1: class extends self.ISpriteInstance {},
	BackgroundStart: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	DeathBackground: class extends self.ISpriteInstance {},
	TryAgain: class extends self.ISpriteInstance {},
	Quit: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	BackgroundTimeZone: class extends self.ISpriteInstance {},
	TimerBox: class extends self.ISpriteInstance {},
	Timer: class extends self.ITextInstance {},
	BackgroundGinger: class extends self.ISpriteInstance {},
	PlatformGinger: class extends self.ISpriteInstance {},
	TimeEater: class extends self.ISpriteInstance {},
	TimeBullet: class extends self.ISpriteInstance {},
	TimeEaterSprite: class extends self.ISpriteInstance {},
	HP: class extends self.ITextInstance {},
	MrChidester: class extends self.ISpriteInstance {},
	BackgroundWin: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	TimeHole: class extends self.ISpriteInstance {},
	TimeHoleEnd: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}